import { defineConfig } from 'astro/config';

// Static output. Vercel auto-detects Astro and serves dist/ with zero config.
// Sitemap is generated by src/pages/sitemap.xml.ts from the same data the
// pages are built from, so it cannot drift out of sync with real routes.
export default defineConfig({
  // Canonical origin. Set PUBLIC_SITE_URL in the host's environment to
  // override without a code change — it drives canonical URLs, the sitemap
  // and the absolute OG image URLs, all of which are wrong until it is right.
  // Canonical origin. Set PUBLIC_SITE_URL in the host's environment to override
  // without a code change — it drives canonical URLs, the sitemap and the
  // absolute OG image URLs.
  //
  // The fallback is the domain actually serving the site, not the one it will
  // eventually move to. It used to be texasallsheds.com, which has no DNS record:
  // canonical pointed at nothing and every og:image resolved to a dead host, so
  // sharing a link produced no preview at all. A fallback that is merely
  // aspirational is worse than none — nothing fails loudly, the previews are
  // just silently blank.
  site: process.env.PUBLIC_SITE_URL ?? 'https://texas-all-sheds.vercel.app',
  output: 'static',
  build: { format: 'directory' },
  compressHTML: true,
});
