import { defineConfig } from 'astro/config';

// Static output. Vercel auto-detects Astro and serves dist/ with zero config.
// Sitemap is generated by src/pages/sitemap.xml.ts from the same data the
// pages are built from, so it cannot drift out of sync with real routes.
export default defineConfig({
  // Canonical origin. Set PUBLIC_SITE_URL in the host's environment to
  // override without a code change — it drives canonical URLs, the sitemap
  // and the absolute OG image URLs, all of which are wrong until it is right.
  site: process.env.PUBLIC_SITE_URL ?? 'https://texasallsheds.com',
  output: 'static',
  build: { format: 'directory' },
  compressHTML: true,
});
